import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { CheckCircle2, AlertTriangle, X } from 'lucide-react';
import { ImportedStudent, ExcelImportResult } from '@/utils/excelImport';

interface ExcelPreviewProps {
  result: ExcelImportResult;
  onConfirm: () => void;
  onCancel: () => void;
}

export function ExcelPreview({ result, onConfirm, onCancel }: ExcelPreviewProps) {
  const previewStudents = result.students.slice(0, 5);
  const hasMore = result.students.length > 5;
  
  return (
    <Card className="border-2 border-primary/20 bg-card">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg font-heading">Excel Preview</CardTitle>
          <Button variant="ghost" size="sm" onClick={onCancel} className="h-8 w-8 p-0">
            <X className="h-4 w-4" />
          </Button>
        </div>
        <p className="text-sm text-muted-foreground">
          Found {result.students.length} students. Review before importing.
        </p>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Auto-generated column indicators */}
        {(result.autoGenerated.serialNumber || result.autoGenerated.studentName || result.autoGenerated.enrollmentNumber) && (
          <div className="flex flex-wrap gap-2">
            {result.autoGenerated.serialNumber && (
              <Badge variant="secondary" className="gap-1">
                <AlertTriangle className="h-3 w-3" />
                S.No auto-generated
              </Badge>
            )}
            {result.autoGenerated.studentName && (
              <Badge variant="secondary" className="gap-1">
                <AlertTriangle className="h-3 w-3" />
                Names auto-generated
              </Badge>
            )}
            {result.autoGenerated.enrollmentNumber && (
              <Badge variant="secondary" className="gap-1">
                <AlertTriangle className="h-3 w-3" />
                Enrollment auto-generated
              </Badge>
            )}
          </div>
        )}

        {/* Warnings */}
        {result.warnings.length > 0 && (
          <div className="bg-muted/50 rounded-lg p-3 space-y-1">
            <p className="text-sm font-medium text-muted-foreground">Auto-corrections made:</p>
            {result.warnings.map((warning, i) => (
              <p key={i} className="text-xs text-muted-foreground">• {warning}</p>
            ))}
          </div>
        )}

        {/* Preview Table */}
        <div className="overflow-x-auto rounded-lg border border-border">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-muted">
                <th className="px-3 py-2 text-left font-medium">S.No</th>
                <th className="px-3 py-2 text-left font-medium">Student Name</th>
                <th className="px-3 py-2 text-left font-medium">Enrollment No</th>
                <th className="px-3 py-2 text-left font-medium">Subjects</th>
              </tr>
            </thead>
            <tbody>
              {previewStudents.map((student, idx) => (
                <tr key={idx} className="border-t border-border">
                  <td className="px-3 py-2 font-mono">{student.serialNo}</td>
                  <td className="px-3 py-2">
                    {student.name}
                    {result.autoGenerated.studentName && student.name.startsWith('Student ') && (
                      <Badge variant="outline" className="ml-2 text-xs">auto</Badge>
                    )}
                  </td>
                  <td className="px-3 py-2 font-mono text-xs">
                    {student.enrollmentNumber}
                    {result.autoGenerated.enrollmentNumber && student.enrollmentNumber.startsWith('ENR') && (
                      <Badge variant="outline" className="ml-2 text-xs">auto</Badge>
                    )}
                  </td>
                  <td className="px-3 py-2">
                    {student.subjectMarks && Object.keys(student.subjectMarks).length > 0 ? (
                      <span className="text-xs text-muted-foreground">
                        {Object.keys(student.subjectMarks).length} subjects
                      </span>
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {hasMore && (
          <p className="text-sm text-muted-foreground text-center">
            + {result.students.length - 5} more students
          </p>
        )}

        {/* Action Buttons */}
        <div className="flex gap-3 justify-end pt-2">
          <Button variant="outline" onClick={onCancel}>
            Cancel
          </Button>
          <Button onClick={onConfirm} className="gap-2">
            <CheckCircle2 className="h-4 w-4" />
            Import {result.students.length} Students
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
