import * as XLSX from 'xlsx';
import { Student, createEmptyStudent, calculatePercentage, getMoodFromPerformance, SKILL_OPTIONS } from '@/types/assessment';

export interface ImportedStudent {
  serialNo: number; // Primary identifier (GUARANTEED - from Excel or auto-generated)
  enrollmentNumber: string; // Unique student ID (GUARANTEED - from Excel or auto-generated)
  name: string; // Student name (GUARANTEED - from Excel or auto-generated)
  rollNumber: string;
  className?: string;
  section?: string;
  subjectMarks?: Record<string, number>;
  attendancePresent?: number;
  attendanceTotal?: number;
  behaviorNotes?: string;
}

/**
 * Result of Excel parsing - includes metadata about auto-generation
 */
export interface ExcelImportResult {
  students: ImportedStudent[];
  autoGenerated: {
    serialNumber: boolean; // True if S.No was auto-generated
    studentName: boolean; // True if Name column was missing/auto-filled
    enrollmentNumber: boolean; // True if Enrollment was auto-generated
  };
  headers: string[]; // Original headers for reference
  warnings: string[]; // Friendly messages about what was auto-generated
}
/**
 * Smart Column Detection & Auto-Generation Logic
 * 
 * GUARANTEED OUTPUT COLUMNS:
 * 1. Serial Number (S.No) - Auto-generated 1..N if missing
 * 2. Student Name - Auto-generated "Student 1", "Student 2"... if missing
 * 3. Enrollment Number - Auto-generated "ENR001", "ENR002"... if missing
 * 
 * NO HARD ERRORS: Missing columns are auto-filled with friendly warnings.
 * 
 * Detection logic:
 * 1. Normalize headers: trim whitespace, convert to lowercase
 * 2. Check against known variations (exact or partial matches)
 * 3. If column missing → auto-generate values
 * 4. If column exists but has blanks → fill blanks with auto-generated values
 */

// Accepted variations for each field type
const NAME_VARIATIONS = [
  'name', 'student name', 'full name', 'student', 'student_name', 
  'studentname', 'child name', 'learner name', "student's name",
  'pupil name', 'scholar name', 'candidate name'
];

/**
 * Serial Number variations - Primary identifier from Excel
 * Extended list for better detection (case-insensitive)
 */
const SERIAL_VARIATIONS = [
  'serial', 'serial no', 'serial number', 's.no', 's no', 'sno', 'sr no', 
  'sr. no', 'sr.no', 'sr', 's.no.', 'sl no', 'sl. no', 'slno', 'sl',
  'sr.', 'srno', 's. no', 's. no.', 'serial no.', 'sr. no.'
];

/**
 * Additional keywords that indicate a Serial Number column
 * Used as fallback detection
 */
const SERIAL_KEYWORDS = ['serial', 'sr', 's.no'];

/**
 * Enrollment Number variations - Unique student ID shown on reports
 * This is the student's official ID for reports and PDFs
 */
const ENROLLMENT_VARIATIONS = [
  'enrollment', 'enrollment no', 'enrollment number', 'enroll no', 'enroll',
  'enrolment', 'enrolment no', 'enrolment number', 'admission no', 'adm no',
  'adm. no', 'admission number', 'student id', 'id no', 'id number', 'reg no',
  'registration no', 'registration number', 'uid', 'unique id'
];

/**
 * Roll Number variations - Kept separate from Serial/Enrollment
 */
const ROLL_VARIATIONS = [
  'roll', 'roll no', 'roll number', 'rollno', 'roll no.', 'roll_no'
];

const CLASS_VARIATIONS = [
  'class', 'grade', 'standard', 'std', 'form', 'year', 'level'
];

const SECTION_VARIATIONS = [
  'section', 'div', 'division', 'sec', 'stream', 'batch'
];

const ATTENDANCE_PRESENT_VARIATIONS = [
  'present', 'days present', 'attendance present', 'present days',
  'attended', 'days attended'
];

const ATTENDANCE_TOTAL_VARIATIONS = [
  'total days', 'working days', 'total', 'attendance total',
  'school days', 'total working days'
];

const BEHAVIOR_VARIATIONS = [
  'behavior', 'behaviour', 'notes', 'remarks', 'teacher notes',
  'behavior notes', 'behaviour notes', 'comment', 'comments',
  'teacher comment', 'observation', 'observations'
];

/**
 * Parses an Excel file and extracts student data
 * 
 * GUARANTEES: Output always contains these 3 columns:
 * - Serial Number (S.No): From Excel or auto-generated 1..N
 * - Student Name: From Excel or auto-generated "Student 1", "Student 2"...
 * - Enrollment Number: From Excel or auto-generated "ENR001", "ENR002"...
 * 
 * NO HARD ERRORS for missing columns - they are auto-generated with warnings.
 */
export async function importStudentsFromExcel(file: File): Promise<ExcelImportResult> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const data = new Uint8Array(e.target?.result as ArrayBuffer);
        const workbook = XLSX.read(data, { type: 'array' });
        
        const sheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[sheetName];
        const jsonData = XLSX.utils.sheet_to_json(worksheet, { header: 1 }) as any[][];
        
        if (jsonData.length < 2) {
          reject(new Error('Excel file must have at least a header row and one data row'));
          return;
        }
        
        // Normalize headers: trim extra spaces and convert to lowercase
        const rawHeaders = jsonData[0].map((h: any) => String(h || ''));
        const headerRow = rawHeaders.map(h => h.toLowerCase().trim().replace(/\s+/g, ' '));
        
        const warnings: string[] = [];
        
        // Track what was auto-generated
        const autoGenerated = {
          serialNumber: false,
          studentName: false,
          enrollmentNumber: false,
        };
        
        /**
         * COLUMN DETECTION
         * All 3 required columns use flexible detection with auto-generation fallback
         */
        
        // ===== A) SERIAL NUMBER DETECTION =====
        let serialColIndex = findSmartColumnIndex(headerRow, SERIAL_VARIATIONS, jsonData);
        
        // Fallback: Check if any header contains serial keywords
        if (serialColIndex === -1) {
          for (const keyword of SERIAL_KEYWORDS) {
            serialColIndex = findColumnContaining(headerRow, keyword, jsonData);
            if (serialColIndex !== -1) break;
          }
        }
        
        if (serialColIndex === -1) {
          autoGenerated.serialNumber = true;
          warnings.push("Serial Number (S.No) column not found → Auto-generated (1, 2, 3...)");
        }
        
        // ===== B) STUDENT NAME DETECTION =====
        let nameColIndex = findSmartColumnIndex(headerRow, NAME_VARIATIONS, jsonData);
        if (nameColIndex === -1) {
          nameColIndex = findColumnContaining(headerRow, 'name', jsonData);
        }
        
        if (nameColIndex === -1) {
          autoGenerated.studentName = true;
          warnings.push("Student Name column not found → Auto-generated (Student 1, Student 2...)");
        }
        
        // ===== C) ENROLLMENT NUMBER DETECTION =====
        const enrollmentColIndex = findSmartColumnIndex(headerRow, ENROLLMENT_VARIATIONS, jsonData);
        
        if (enrollmentColIndex === -1) {
          autoGenerated.enrollmentNumber = true;
          warnings.push("Enrollment Number column not found → Auto-generated (ENR001, ENR002...)");
        }
        
        // Detect other optional columns
        const rollColIndex = findSmartColumnIndex(headerRow, ROLL_VARIATIONS, jsonData);
        const classColIndex = findSmartColumnIndex(headerRow, CLASS_VARIATIONS, jsonData);
        const sectionColIndex = findSmartColumnIndex(headerRow, SECTION_VARIATIONS, jsonData);
        const attendancePresentIndex = findSmartColumnIndex(headerRow, ATTENDANCE_PRESENT_VARIATIONS, jsonData);
        const attendanceTotalIndex = findSmartColumnIndex(headerRow, ATTENDANCE_TOTAL_VARIATIONS, jsonData);
        const behaviorIndex = findSmartColumnIndex(headerRow, BEHAVIOR_VARIATIONS, jsonData);
        
        // Find subject columns (anything with marks, score, or known subject names)
        const subjectColumns = findSubjectColumns(headerRow);
        
        // Extract student data with GUARANTEED columns
        const students: ImportedStudent[] = [];
        const serialNumbers = new Set<number>(); // Track for duplicate detection
        let autoSerialCounter = 0; // For auto-generation
        let nameAutoFillCount = 0; // Track how many names were auto-filled
        let enrollmentAutoFillCount = 0; // Track how many enrollments were auto-filled
        
        for (let i = 1; i < jsonData.length; i++) {
          const row = jsonData[i];
          
          // Skip completely empty rows
          const hasAnyData = row.some((cell: any) => cell !== undefined && cell !== null && String(cell).trim() !== '');
          if (!hasAnyData) continue;
          
          autoSerialCounter++; // Always increment for potential auto-generation
          
          // ===== A) SERIAL NUMBER - GUARANTEED =====
          let serialNo: number;
          
          if (autoGenerated.serialNumber || serialColIndex === -1) {
            // Auto-generate sequential S.No
            serialNo = autoSerialCounter;
          } else {
            // Extract from Excel column
            const rawSerial = row[serialColIndex];
            serialNo = parseInt(String(rawSerial || ''));
            
            // If invalid, auto-generate for this row
            if (isNaN(serialNo) || serialNo <= 0) {
              serialNo = autoSerialCounter;
            }
          }
          
          // Handle duplicate serial numbers by auto-incrementing
          if (serialNumbers.has(serialNo)) {
            const originalSerial = serialNo;
            while (serialNumbers.has(serialNo)) {
              serialNo++;
            }
            if (!autoGenerated.serialNumber) {
              warnings.push(`Duplicate S.No ${originalSerial} → auto-fixed to ${serialNo}`);
            }
          }
          serialNumbers.add(serialNo);
          
          // ===== B) STUDENT NAME - GUARANTEED =====
          let name: string;
          
          if (autoGenerated.studentName || nameColIndex === -1) {
            // Column missing - auto-generate all names
            name = `Student ${serialNo}`;
          } else {
            // Column exists - extract value or fill blank
            const rawName = String(row[nameColIndex] || '').trim();
            if (rawName) {
              name = rawName;
            } else {
              // Blank value - auto-fill
              name = `Student ${serialNo}`;
              nameAutoFillCount++;
            }
          }
          
          // ===== C) ENROLLMENT NUMBER - GUARANTEED =====
          let enrollmentNumber: string;
          
          if (autoGenerated.enrollmentNumber || enrollmentColIndex === -1) {
            // Column missing - auto-generate all enrollments
            enrollmentNumber = `ENR${String(serialNo).padStart(3, '0')}`;
          } else {
            // Column exists - extract value or fill blank
            const rawEnrollment = String(row[enrollmentColIndex] || '').trim();
            if (rawEnrollment) {
              enrollmentNumber = rawEnrollment;
            } else {
              // Blank value - auto-fill
              enrollmentNumber = `ENR${String(serialNo).padStart(3, '0')}`;
              enrollmentAutoFillCount++;
            }
          }
          
          // Extract subject marks
          const subjectMarks: Record<string, number> = {};
          subjectColumns.forEach(({ index, name: subjectName }) => {
            const value = row[index];
            if (value !== undefined && value !== null && value !== '') {
              const numValue = parseFloat(String(value));
              if (!isNaN(numValue)) {
                subjectMarks[subjectName] = Math.min(100, Math.max(0, numValue));
              }
            }
          });
          
          // Extract attendance with safe parsing
          let attendancePresent = 0;
          let attendanceTotal = 0;
          if (attendancePresentIndex !== -1) {
            attendancePresent = parseInt(String(row[attendancePresentIndex] || 0)) || 0;
          }
          if (attendanceTotalIndex !== -1) {
            attendanceTotal = parseInt(String(row[attendanceTotalIndex] || 0)) || 0;
          }
          
          students.push({
            serialNo,
            enrollmentNumber,
            name,
            rollNumber: rollColIndex !== -1 ? String(row[rollColIndex] || '').trim() : '',
            className: classColIndex !== -1 ? String(row[classColIndex] || '').trim() : undefined,
            section: sectionColIndex !== -1 ? String(row[sectionColIndex] || '').trim() : undefined,
            subjectMarks: Object.keys(subjectMarks).length > 0 ? subjectMarks : undefined,
            attendancePresent,
            attendanceTotal,
            behaviorNotes: behaviorIndex !== -1 ? String(row[behaviorIndex] || '').trim() : undefined,
          });
        }
        
        if (students.length === 0) {
          reject(new Error('No valid student data found in the Excel file. Please ensure there are rows with data.'));
          return;
        }
        
        // Add warnings for partial auto-fills (column existed but had blanks)
        if (nameAutoFillCount > 0 && !autoGenerated.studentName) {
          warnings.push(`${nameAutoFillCount} blank Student Name(s) → auto-filled`);
        }
        if (enrollmentAutoFillCount > 0 && !autoGenerated.enrollmentNumber) {
          warnings.push(`${enrollmentAutoFillCount} blank Enrollment Number(s) → auto-filled`);
        }
        
        // Return result with metadata
        resolve({
          students,
          autoGenerated,
          headers: rawHeaders,
          warnings,
        });
      } catch (error) {
        console.error('Excel parse error:', error);
        reject(new Error('Failed to parse Excel file. Please ensure it is a valid .xlsx or .xls file.'));
      }
    };
    
    reader.onerror = () => {
      reject(new Error('Failed to read the file'));
    };
    
    reader.readAsArrayBuffer(file);
  });
}

/**
 * Smart Column Index Finder
 * 
 * Detection logic:
 * 1. Trim and normalize all headers to lowercase
 * 2. Check if any header exactly matches a known variation
 * 3. Check if any header contains a known variation as substring
 * 4. If multiple matches found, pick the column with most unique non-empty values
 * 
 * @param headers - Normalized (lowercase, trimmed) header array
 * @param variations - Array of known acceptable column name variations
 * @param jsonData - Full data for counting unique values if needed
 * @returns Column index or -1 if not found
 */
function findSmartColumnIndex(
  headers: string[], 
  variations: string[],
  jsonData?: any[][]
): number {
  const matchedIndices: number[] = [];
  
  // First pass: exact matches (header equals variation)
  for (let i = 0; i < headers.length; i++) {
    const header = headers[i];
    if (variations.includes(header)) {
      matchedIndices.push(i);
    }
  }
  
  // Second pass: partial matches (header contains variation)
  if (matchedIndices.length === 0) {
    for (let i = 0; i < headers.length; i++) {
      const header = headers[i];
      for (const variation of variations) {
        if (header.includes(variation)) {
          matchedIndices.push(i);
          break; // Avoid adding same index multiple times
        }
      }
    }
  }
  
  // No matches found
  if (matchedIndices.length === 0) {
    return -1;
  }
  
  // Single match - return it
  if (matchedIndices.length === 1) {
    return matchedIndices[0];
  }
  
  // Multiple matches - pick column with most unique non-empty values
  if (jsonData && jsonData.length > 1) {
    let bestIndex = matchedIndices[0];
    let maxUniqueCount = 0;
    
    for (const colIndex of matchedIndices) {
      const uniqueValues = new Set<string>();
      for (let row = 1; row < jsonData.length; row++) {
        const value = String(jsonData[row][colIndex] || '').trim();
        if (value) {
          uniqueValues.add(value);
        }
      }
      
      if (uniqueValues.size > maxUniqueCount) {
        maxUniqueCount = uniqueValues.size;
        bestIndex = colIndex;
      }
    }
    
    return bestIndex;
  }
  
  // Fallback to first match
  return matchedIndices[0];
}

/**
 * Fallback finder: looks for any column header containing a keyword
 * Used when specific variations don't match
 * 
 * @param headers - Normalized header array
 * @param keyword - Keyword to search for (e.g., "name")
 * @param jsonData - Full data for tie-breaking
 * @returns Column index or -1 if not found
 */
function findColumnContaining(
  headers: string[], 
  keyword: string,
  jsonData?: any[][]
): number {
  const matchedIndices: number[] = [];
  
  // Find all columns containing the keyword
  for (let i = 0; i < headers.length; i++) {
    if (headers[i].includes(keyword.toLowerCase())) {
      matchedIndices.push(i);
    }
  }
  
  if (matchedIndices.length === 0) {
    return -1;
  }
  
  if (matchedIndices.length === 1) {
    return matchedIndices[0];
  }
  
  // Multiple matches: pick column with most unique non-empty values
  if (jsonData && jsonData.length > 1) {
    let bestIndex = matchedIndices[0];
    let maxUniqueCount = 0;
    
    for (const colIndex of matchedIndices) {
      const uniqueValues = new Set<string>();
      for (let row = 1; row < jsonData.length; row++) {
        const value = String(jsonData[row][colIndex] || '').trim();
        if (value) {
          uniqueValues.add(value);
        }
      }
      
      if (uniqueValues.size > maxUniqueCount) {
        maxUniqueCount = uniqueValues.size;
        bestIndex = colIndex;
      }
    }
    
    return bestIndex;
  }
  
  return matchedIndices[0];
}

// Known subject names for auto-detection
const KNOWN_SUBJECTS = [
  'english', 'hindi', 'mathematics', 'maths', 'math', 'science', 'social', 'sst',
  'computer', 'computers', 'art', 'craft', 'physical', 'pe', 'music', 'sanskrit',
  'evs', 'environmental', 'gk', 'general knowledge', 'drawing', 'moral',
  'reading', 'writing', 'vocabulary', 'grammar', 'listening', 'speaking'
];

function findSubjectColumns(headers: string[]): { index: number; name: string }[] {
  const subjectCols: { index: number; name: string }[] = [];
  
  headers.forEach((header, index) => {
    const lower = header.toLowerCase();
    
    // Check if it's a known subject
    const isKnownSubject = KNOWN_SUBJECTS.some(subject => lower.includes(subject));
    
    // Check if it contains marks/score keywords
    const isMarksColumn = lower.includes('marks') || lower.includes('score') || lower.includes('grade');
    
    if (isKnownSubject || isMarksColumn) {
      // Clean up the subject name
      let subjectName = header
        .replace(/marks?/gi, '')
        .replace(/score/gi, '')
        .replace(/grade/gi, '')
        .replace(/\(\d+\)/g, '') // Remove (100), (50) etc
        .trim();
      
      // Capitalize first letter
      subjectName = subjectName.charAt(0).toUpperCase() + subjectName.slice(1);
      
      // Map common abbreviations
      const abbrevMap: Record<string, string> = {
        'Maths': 'Mathematics',
        'Math': 'Mathematics',
        'Sst': 'Social Studies',
        'Social': 'Social Studies',
        'Pe': 'Physical Education',
        'Physical': 'Physical Education',
        'Evs': 'Environmental Studies',
        'Gk': 'General Knowledge',
        'Comp': 'Computer Science',
        'Computers': 'Computer Science',
      };
      
      subjectName = abbrevMap[subjectName] || subjectName;
      
      if (subjectName) {
        subjectCols.push({ index, name: subjectName });
      }
    }
  });
  
  return subjectCols;
}

/**
 * Converts imported student data to full Student objects
 * 
 * GUARANTEED: All students have Serial Number, Name, and Enrollment Number
 * (either from Excel or auto-generated during import)
 */
export function createStudentsFromImport(
  importedStudents: ImportedStudent[],
  selectedSubjects: string[]
): Student[] {
  // Sort by Serial Number for consistent ordering
  const sortedStudents = [...importedStudents].sort((a, b) => a.serialNo - b.serialNo);
  
  return sortedStudents.map((imported) => {
    // Create student with imported serial number
    const student = createEmptyStudent(imported.serialNo, selectedSubjects);
    
    // Set GUARANTEED identifiers (all populated during import)
    student.serialNo = imported.serialNo;
    student.enrollmentNumber = imported.enrollmentNumber; // Always a string now
    student.name = imported.name; // Always a string now
    student.rollNumber = imported.rollNumber;
    
    // Set subject marks if provided
    if (imported.subjectMarks) {
      Object.entries(imported.subjectMarks).forEach(([subject, marks]) => {
        student.subjectMarks[subject] = marks;
        // Auto-generate rating from marks
        if (marks >= 85) student.subjectRatings[subject] = 'Excellent';
        else if (marks >= 70) student.subjectRatings[subject] = 'Good';
        else if (marks >= 50) student.subjectRatings[subject] = 'Average';
        else student.subjectRatings[subject] = 'Needs Improvement';
      });
    }
    
    // Set attendance
    if (imported.attendancePresent !== undefined) {
      student.attendancePresent = imported.attendancePresent;
    }
    if (imported.attendanceTotal !== undefined) {
      student.attendanceTotal = imported.attendanceTotal;
      student.attendancePercentage = imported.attendanceTotal > 0 
        ? Math.round((imported.attendancePresent || 0) / imported.attendanceTotal * 100)
        : 0;
    }
    
    // Set behavior notes
    if (imported.behaviorNotes) {
      student.behaviorNotes = imported.behaviorNotes;
      student.teacherNotes = imported.behaviorNotes;
    }
    
    // Calculate percentage from marks
    student.percentage = calculatePercentage(student.subjectMarks);
    student.moodRating = getMoodFromPerformance(student.percentage);
    
    return student;
  });
}

/**
 * Generates a sample Excel template for teachers
 * 
 * GUARANTEED COLUMNS (all 3 will be present in output even if missing from upload):
 * 1. S.No (Serial Number) - Primary identifier
 * 2. Student Name - Student's name
 * 3. Enrollment No - Unique ID for reports
 * 
 * Plus other optional columns (Roll No, Class, Subjects, etc.)
 */
export function generateSampleTemplate(): void {
  const wb = XLSX.utils.book_new();
  
  // Template with Serial Number as mandatory column
  // Name and Enrollment are optional but shown as examples
  const sampleData = [
    ['S.No', 'Enrollment No', 'Student Name', 'Roll No', 'Class', 'Section', 'English', 'Hindi', 'Mathematics', 'Science', 'Social Studies', 'Days Present', 'Total Days', 'Behavior Notes'],
    [1, 'ENR-001', 'Aarav Sharma', '1', '5', 'A', 85, 78, 92, 88, 75, 45, 50, 'Very attentive and helpful'],
    [2, 'ENR-002', 'Priya Patel', '2', '5', 'A', 90, 85, 78, 82, 88, 48, 50, 'Excellent participation'],
    [3, 'ENR-003', 'Rahul Kumar', '3', '5', 'A', 72, 68, 65, 70, 72, 40, 50, 'Needs to be more focused'],
  ];
  
  const ws = XLSX.utils.aoa_to_sheet(sampleData);
  
  ws['!cols'] = [
    { wch: 8 },  // S.No
    { wch: 14 }, // Enrollment No
    { wch: 20 }, // Student Name
    { wch: 8 },  // Roll No
    { wch: 8 },  // Class
    { wch: 8 },  // Section
    { wch: 10 }, // English
    { wch: 10 }, // Hindi
    { wch: 12 }, // Mathematics
    { wch: 10 }, // Science
    { wch: 14 }, // Social Studies
    { wch: 12 }, // Days Present
    { wch: 10 }, // Total Days
    { wch: 30 }, // Behavior Notes
  ];
  
  XLSX.utils.book_append_sheet(wb, ws, 'Student Data');
  XLSX.writeFile(wb, 'Student_Import_Template.xlsx');
}
