import * as XLSX from 'xlsx';
import { Student, createEmptyStudent, calculatePercentage, getMoodFromPerformance, SKILL_OPTIONS } from '@/types/assessment';
import { standardizeSubjectName } from '@/utils/subjectMapper';
export interface ImportedStudent {
  serialNo: number;
  enrollmentNumber: string;
  name: string;
  rollNumber: string;
  className?: string;
  section?: string;
  subjectMarks?: Record<string, number>;
  attendancePresent?: number;
  attendanceTotal?: number;
  behaviorNotes?: string;
}

export interface ExcelImportResult {
  students: ImportedStudent[];
  autoGenerated: {
    serialNumber: boolean;
  };
  headers: string[];
  headerRowIndex: number;
  detectedColumns: {
    serialNo: { index: number; header: string } | null;
    name: { index: number; header: string } | null;
    enrollment: { index: number; header: string } | null;
  };
  detectedSubjects: string[];  // Subjects detected from Excel headers
  warnings: string[];
}

/**
 * =============================================================
 * ROBUST EXCEL IMPORT ENGINE
 * =============================================================
 * 
 * Features:
 * - Scans first 20 rows to find the header row
 * - Handles messy files with title rows, blank rows, merged cells
 * - Case-insensitive header matching
 * - Auto-generates S.No if missing, but never auto-generates names/enrollment
 */

/**
 * Normalize a header string for comparison
 */
function normalizeHeader(header: string): string {
  return String(header || '').toLowerCase().trim().replace(/\s+/g, ' ').replace(/[.\-_]/g, '');
}

// =============================================================
// HEADER PATTERNS
// =============================================================

const SERIAL_PATTERNS = [
  's.no', 'sno', 's no', 'sr no', 'sr.no', 'srno', 'sr. no',
  'serial', 'serial no', 'serial number', 'sl no', 'sl.no', 'slno',
  's. no', 's.no.', 'sr.no.', 'sl. no', 'sr', 'sl'
];

const NAME_PATTERNS = [
  'student name', 'studentname', 'name', 'student', 'full name',
  "student's name", 'child name', 'learner name', 'pupil name',
  'scholar name', 'candidate name', 'name of student'
];

const ENROLLMENT_PATTERNS = [
  'enrollment no', 'enrollment number', 'enrollment', 'enroll no',
  'enrolment no', 'enrolment number', 'enrolment', 
  'er no', 'er.no', 'er. no', 'erno',
  'adm no', 'adm.no', 'adm. no', 'admission no', 'admission number', 'admission',
  'student id', 'id no', 'id number',
  'reg no', 'registration no', 'registration number',
  'uid', 'unique id', 'en.no', 'en no', 'enno'
];

const ROLL_PATTERNS = [
  'roll', 'roll no', 'roll number', 'rollno', 'roll no.'
];

const CLASS_PATTERNS = [
  'class', 'grade', 'standard', 'std', 'form', 'year', 'level'
];

const SECTION_PATTERNS = [
  'section', 'div', 'division', 'sec', 'stream', 'batch'
];

const ATTENDANCE_PRESENT_PATTERNS = [
  'present', 'days present', 'attendance present', 'present days', 'attended'
];

const ATTENDANCE_TOTAL_PATTERNS = [
  'total days', 'working days', 'attendance total', 'school days'
];

const BEHAVIOR_PATTERNS = [
  'behavior', 'behaviour', 'notes', 'remarks', 'teacher notes', 'comment',
  'comments', 'observation', 'observations'
];

const KNOWN_SUBJECTS = [
  'english', 'hindi', 'mathematics', 'maths', 'math', 'science', 'social studies',
  'social science', 'sst', 'computer', 'computer science', 'cs', 'art', 'craft',
  'art & craft', 'physical education', 'pe', 'music', 'drawing', 'gk', 
  'general knowledge', 'evs', 'environmental studies', 'sanskrit', 'urdu',
  'french', 'german', 'physics', 'chemistry', 'biology', 'economics', 'history',
  'geography', 'civics', 'accountancy', 'business studies', 'commerce'
];

/**
 * Check if a normalized header matches any pattern
 */
function matchesPattern(normalizedHeader: string, patterns: string[]): boolean {
  for (const pattern of patterns) {
    const normalizedPattern = normalizeHeader(pattern);
    // Exact match
    if (normalizedHeader === normalizedPattern) return true;
    // Contains match (header contains pattern or pattern contains header)
    if (normalizedHeader.includes(normalizedPattern) || normalizedPattern.includes(normalizedHeader)) {
      return true;
    }
  }
  return false;
}

/**
 * Find column by patterns in a row
 */
function findColumnByPatterns(
  row: any[],
  patterns: string[]
): { index: number; header: string } | null {
  for (let i = 0; i < row.length; i++) {
    const cellValue = String(row[i] || '').trim();
    if (!cellValue) continue;
    
    const normalized = normalizeHeader(cellValue);
    if (matchesPattern(normalized, patterns)) {
      return { index: i, header: cellValue };
    }
  }
  return null;
}

/**
 * Count how many key columns are found in a row
 * Key columns: Name + Enrollment OR Name + S.No (at least 2 of 3)
 */
function countKeyColumns(row: any[]): {
  count: number;
  hasName: boolean;
  hasEnrollment: boolean;
  hasSerial: boolean;
} {
  const hasName = findColumnByPatterns(row, NAME_PATTERNS) !== null;
  const hasEnrollment = findColumnByPatterns(row, ENROLLMENT_PATTERNS) !== null;
  const hasSerial = findColumnByPatterns(row, SERIAL_PATTERNS) !== null;
  
  let count = 0;
  if (hasName) count++;
  if (hasEnrollment) count++;
  if (hasSerial) count++;
  
  return { count, hasName, hasEnrollment, hasSerial };
}

/**
 * Scan first N rows to find the header row
 * Returns the row index (0-based) or -1 if not found
 */
function findHeaderRow(jsonData: any[][], maxRows: number = 20): number {
  const rowsToScan = Math.min(jsonData.length, maxRows);
  
  let bestRowIndex = -1;
  let bestScore = 0;
  
  for (let i = 0; i < rowsToScan; i++) {
    const row = jsonData[i];
    if (!row || row.length === 0) continue;
    
    // Skip rows that are completely empty or have only one cell (likely title)
    const nonEmptyCells = row.filter((cell: any) => 
      cell !== undefined && cell !== null && String(cell).trim() !== ''
    );
    if (nonEmptyCells.length < 2) continue;
    
    const { count, hasName, hasEnrollment } = countKeyColumns(row);
    
    // We need at least Name + one other (Enrollment or S.No)
    if (count >= 2 && hasName) {
      // Prefer rows with Name + Enrollment
      const score = hasEnrollment ? count + 1 : count;
      if (score > bestScore) {
        bestScore = score;
        bestRowIndex = i;
      }
    }
  }
  
  return bestRowIndex;
}

/**
 * Check if a cell value is empty
 */
function isEmptyCell(value: any): boolean {
  if (value === undefined || value === null) return true;
  const str = String(value).trim();
  return str === '' || str === '-' || str === 'N/A' || str === 'NA' || str === '—';
}

/**
 * Detect subject columns
 */
function findSubjectColumns(
  rawHeaders: string[],
  jsonData: any[][],
  headerRowIndex: number,
  excludeIndices: Set<number>
): { index: number; name: string }[] {
  const subjects: { index: number; name: string }[] = [];
  
  for (let i = 0; i < rawHeaders.length; i++) {
    if (excludeIndices.has(i)) continue;
    
    const header = rawHeaders[i];
    if (!header) continue;
    
    const normalized = normalizeHeader(header);
    
    // Check if it's a known subject
    let isSubject = KNOWN_SUBJECTS.some(subj => 
      normalized.includes(normalizeHeader(subj)) || normalizeHeader(subj).includes(normalized)
    );
    
    // Also check if the column contains mostly numeric data (marks)
    if (!isSubject) {
      let numericCount = 0;
      let totalCount = 0;
      
      for (let row = headerRowIndex + 1; row < Math.min(jsonData.length, headerRowIndex + 10); row++) {
        const value = jsonData[row]?.[i];
        if (value !== undefined && value !== null && String(value).trim() !== '') {
          totalCount++;
          const num = parseFloat(String(value));
          if (!isNaN(num) && num >= 0 && num <= 100) {
            numericCount++;
          }
        }
      }
      
      // If >70% of rows are numeric 0-100, likely a marks column
      if (totalCount > 0 && numericCount / totalCount >= 0.7) {
        isSubject = true;
      }
    }
    
    if (isSubject) {
      // Standardize the subject name for consistent display
      const standardName = standardizeSubjectName(header.trim());
      subjects.push({ index: i, name: standardName });
    }
  }
  
  return subjects;
}

/**
 * Parse Excel file and extract student data
 */
export async function importStudentsFromExcel(file: File): Promise<ExcelImportResult> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const data = new Uint8Array(e.target?.result as ArrayBuffer);
        const workbook = XLSX.read(data, { type: 'array' });
        
        const sheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[sheetName];
        const jsonData = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: '' }) as any[][];
        
        if (jsonData.length < 1) {
          reject(new Error('Excel file is empty'));
          return;
        }
        
        console.log('📊 Scanning Excel for header row...');
        console.log(`   Total rows in file: ${jsonData.length}`);
        
        // =============================================================
        // STEP 1: FIND HEADER ROW
        // =============================================================
        
        const headerRowIndex = findHeaderRow(jsonData, 20);
        
        if (headerRowIndex === -1) {
          reject(new Error('Unrecognized format. Please upload a valid student list with columns like "Student Name" and "Enrollment No".'));
          return;
        }
        
        console.log(`✅ Header row found at row ${headerRowIndex + 1}`);
        
        const headerRow = jsonData[headerRowIndex];
        const rawHeaders = headerRow.map((h: any) => String(h || '').trim());
        
        console.log('📋 Headers detected:', rawHeaders.filter(h => h));
        
        const warnings: string[] = [];
        const autoGenerated = { serialNumber: false };
        
        // =============================================================
        // STEP 2: DETECT COLUMNS
        // =============================================================
        
        // Serial Number column
        const serialCol = findColumnByPatterns(headerRow, SERIAL_PATTERNS);
        if (serialCol) {
          console.log(`✅ S.No column: "${serialCol.header}" (column ${serialCol.index + 1})`);
        } else {
          console.log('⚠️ S.No column not found → will auto-generate');
          autoGenerated.serialNumber = true;
          warnings.push('S.No column not found → Auto-generated sequential numbers');
        }
        
        // Student Name column - REQUIRED
        const nameCol = findColumnByPatterns(headerRow, NAME_PATTERNS);
        if (nameCol) {
          console.log(`✅ Name column: "${nameCol.header}" (column ${nameCol.index + 1})`);
        } else {
          reject(new Error('Student Name column missing. Please ensure your file has a column named "Name", "Student Name", or similar.'));
          return;
        }
        
        // Enrollment Number column - REQUIRED
        const enrollmentCol = findColumnByPatterns(headerRow, ENROLLMENT_PATTERNS);
        if (enrollmentCol) {
          console.log(`✅ Enrollment column: "${enrollmentCol.header}" (column ${enrollmentCol.index + 1})`);
        } else {
          reject(new Error('Enrollment Number column missing. Please ensure your file has a column named "Enrollment No", "Adm No", "ER No", or similar.'));
          return;
        }
        
        // Other columns
        const rollCol = findColumnByPatterns(headerRow, ROLL_PATTERNS);
        const classCol = findColumnByPatterns(headerRow, CLASS_PATTERNS);
        const sectionCol = findColumnByPatterns(headerRow, SECTION_PATTERNS);
        const attendancePresentCol = findColumnByPatterns(headerRow, ATTENDANCE_PRESENT_PATTERNS);
        const attendanceTotalCol = findColumnByPatterns(headerRow, ATTENDANCE_TOTAL_PATTERNS);
        const behaviorCol = findColumnByPatterns(headerRow, BEHAVIOR_PATTERNS);
        
        // Build excluded indices for subject detection
        const excludeIndices = new Set<number>();
        [serialCol, nameCol, enrollmentCol, rollCol, classCol, sectionCol,
         attendancePresentCol, attendanceTotalCol, behaviorCol].forEach(col => {
          if (col) excludeIndices.add(col.index);
        });
        
        // Detect subject columns
        const subjectCols = findSubjectColumns(rawHeaders, jsonData, headerRowIndex, excludeIndices);
        if (subjectCols.length > 0) {
          console.log(`📚 Subject columns: ${subjectCols.map(s => s.name).join(', ')}`);
        }
        
        // =============================================================
        // STEP 3: PARSE STUDENT DATA
        // =============================================================
        
        const students: ImportedStudent[] = [];
        const serialNumbers = new Set<number>();
        let autoSerialCounter = 0;
        let skippedRows = 0;
        
        for (let rowIndex = headerRowIndex + 1; rowIndex < jsonData.length; rowIndex++) {
          const row = jsonData[rowIndex];
          
          // Skip completely empty rows
          const hasAnyData = row.some((cell: any) => !isEmptyCell(cell));
          if (!hasAnyData) continue;
          
          autoSerialCounter++;
          
          // --- Serial Number ---
          let serialNo: number;
          if (serialCol && !isEmptyCell(row[serialCol.index])) {
            serialNo = parseInt(String(row[serialCol.index]));
            if (isNaN(serialNo) || serialNo <= 0) {
              serialNo = autoSerialCounter;
            }
          } else {
            serialNo = autoSerialCounter;
          }
          
          // Handle duplicate serial numbers
          if (serialNumbers.has(serialNo)) {
            const original = serialNo;
            while (serialNumbers.has(serialNo)) {
              serialNo++;
            }
            if (serialCol) {
              warnings.push(`Row ${rowIndex + 1}: Duplicate S.No ${original} → Changed to ${serialNo}`);
            }
          }
          serialNumbers.add(serialNo);
          
          // --- Student Name (use exact value, skip if blank) ---
          if (isEmptyCell(row[nameCol.index])) {
            skippedRows++;
            continue; // Skip rows with blank names
          }
          const name = String(row[nameCol.index]).trim();
          
          // --- Enrollment Number (use exact value, skip if blank) ---
          if (isEmptyCell(row[enrollmentCol.index])) {
            skippedRows++;
            continue; // Skip rows with blank enrollment
          }
          const enrollmentNumber = String(row[enrollmentCol.index]).trim();
          
          // --- Other fields ---
          const rollNumber = rollCol && !isEmptyCell(row[rollCol.index])
            ? String(row[rollCol.index]).trim() : '';
          const className = classCol && !isEmptyCell(row[classCol.index])
            ? String(row[classCol.index]).trim() : undefined;
          const section = sectionCol && !isEmptyCell(row[sectionCol.index])
            ? String(row[sectionCol.index]).trim() : undefined;
          
          // --- Subject Marks ---
          const subjectMarks: Record<string, number> = {};
          subjectCols.forEach(({ index, name: subjectName }) => {
            const value = row[index];
            if (!isEmptyCell(value)) {
              const numValue = parseFloat(String(value));
              if (!isNaN(numValue)) {
                subjectMarks[subjectName] = Math.min(100, Math.max(0, numValue));
              }
            }
          });
          
          // --- Attendance ---
          const attendancePresent = attendancePresentCol && !isEmptyCell(row[attendancePresentCol.index])
            ? parseInt(String(row[attendancePresentCol.index])) || 0 : 0;
          const attendanceTotal = attendanceTotalCol && !isEmptyCell(row[attendanceTotalCol.index])
            ? parseInt(String(row[attendanceTotalCol.index])) || 0 : 0;
          
          // --- Behavior Notes ---
          const behaviorNotes = behaviorCol && !isEmptyCell(row[behaviorCol.index])
            ? String(row[behaviorCol.index]).trim() : undefined;
          
          students.push({
            serialNo,
            enrollmentNumber,
            name,
            rollNumber,
            className,
            section,
            subjectMarks: Object.keys(subjectMarks).length > 0 ? subjectMarks : undefined,
            attendancePresent,
            attendanceTotal,
            behaviorNotes,
          });
        }
        
        if (skippedRows > 0) {
          warnings.push(`${skippedRows} row(s) skipped due to missing Name or Enrollment Number`);
        }
        
        if (students.length === 0) {
          reject(new Error('No valid student data found. Ensure the file has data rows with Student Name and Enrollment Number filled in.'));
          return;
        }
        
        console.log(`✅ Successfully imported ${students.length} students from header row ${headerRowIndex + 1}`);
        if (warnings.length > 0) {
          console.log('⚠️ Warnings:', warnings);
        }
        
        resolve({
          students,
          autoGenerated,
          headers: rawHeaders,
          headerRowIndex: headerRowIndex + 1, // 1-based for display
          detectedColumns: {
            serialNo: serialCol,
            name: nameCol,
            enrollment: enrollmentCol,
          },
          detectedSubjects: subjectCols.map(s => s.name),
          warnings,
        });
      } catch (error) {
        console.error('❌ Excel parse error:', error);
        reject(new Error('Failed to parse Excel file. Please ensure it is a valid .xlsx or .xls file.'));
      }
    };
    
    reader.onerror = () => {
      reject(new Error('Failed to read the file'));
    };
    
    reader.readAsArrayBuffer(file);
  });
}

/**
 * Convert ImportedStudent array to Student objects for the app
 */
export function createStudentsFromImport(
  imported: ImportedStudent[], 
  selectedSubjects: string[]
): Student[] {
  return imported
    .sort((a, b) => a.serialNo - b.serialNo)
    .map((imp) => {
      const subjectMarks: Record<string, number> = {};
      const subjectRatings: Record<string, 'Excellent' | 'Good' | 'Average' | 'Needs Improvement'> = {};
      
      // Map imported subject marks to selected subjects
      selectedSubjects.forEach(subject => {
        const normalizedSubject = subject.toLowerCase();
        let foundMark: number | undefined;
        
        if (imp.subjectMarks) {
          for (const [key, value] of Object.entries(imp.subjectMarks)) {
            if (key.toLowerCase().includes(normalizedSubject) || 
                normalizedSubject.includes(key.toLowerCase())) {
              foundMark = value;
              break;
            }
          }
        }
        
        if (foundMark !== undefined) {
          subjectMarks[subject] = foundMark;
          // Convert marks to ratings
          if (foundMark >= 90) subjectRatings[subject] = 'Excellent';
          else if (foundMark >= 70) subjectRatings[subject] = 'Good';
          else if (foundMark >= 50) subjectRatings[subject] = 'Average';
          else subjectRatings[subject] = 'Needs Improvement';
        }
      });
      
      // Calculate totals
      const totalMarks = Object.values(subjectMarks).reduce((sum, m) => sum + m, 0);
      const maxMarks = Object.keys(subjectMarks).length * 100;
      const percentage = maxMarks > 0 ? Math.round((totalMarks / maxMarks) * 100) : 0;
      
      // Create base student with required fields
      const baseStudent = createEmptyStudent(imp.serialNo, selectedSubjects);
      
      return {
        ...baseStudent,
        id: `student-${imp.serialNo}-${Date.now()}`,
        serialNo: imp.serialNo,
        enrollmentNumber: imp.enrollmentNumber,
        name: imp.name,
        rollNumber: imp.rollNumber,
        className: imp.className,
        section: imp.section,
        subjectMarks,
        subjectRatings,
        total: totalMarks,
        percentage,
        attendancePresent: imp.attendancePresent || 0,
        attendanceTotal: imp.attendanceTotal || 0,
        behaviorNotes: imp.behaviorNotes || '',
        moodRating: getMoodFromPerformance(percentage),
      };
    });
}
